version: '3.9'

services:
  web:
    build: .
    container_name: mydjango
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: 'abcABC123!@#'   # Only root user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
